---
title: "esm_244_lab_9_dn"
author: "Derek Nguyen"
date: "3/5/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(devtools)
library(tidyverse)
library(janitor)
library(here)
library(gt)
library(boot)
library(patchwork)
library(nlstools)
```


### Fun tables with `gt`

LifeCycleSavings
```{r}
disp_income <- LifeCycleSavings %>% 
  rownames_to_column() %>% 
  arrange(dpi) %>% 
  head(5) %>% 
  mutate(ddpi = ddpi / 100,
         pop15 = pop15 / 100,
         pop75 = pop75 / 100)
```


Now lets make a nicer table with `gt`:
```{r}
disp_income %>% 
  gt() %>% 
  tab_header(
    title = "Life Cycle Savings",
    subtitle = "5 countries with lowest per capita income"
  ) %>% 
  fmt_currency(
    columns = vars(dpi),
    decimals = 2
  ) %>% 
  fmt_percent(
    columns = vars(pop15, pop75, ddpi),
    decimals = 1
  ) %>% 
  tab_options(
    table.width = pct(80)
  ) %>% 
  tab_footnote(
    footnote = "Data averaged from 1970 - 1980",
    location = cells_title()
  ) %>% 
  data_color(
    columns = vars(dpi),
    colors = scales::col_numeric(
      palette = c("orange", "purple", "firebrick"),
      domain = c(88, 190)
    )
  ) %>% 
  cols_label(
    sr = "Savings Ratio",
    pop15 = "Pop < 15yr",
    pop75 = "Pop < 75yr",
    dpi = "Disposable $ per capita",
    ddpi = "Disposable percent"
  )
  
```

### Bootstrap Bootstrap the mean salinity: 

```{r}
# View(salinity)

# Get some summary statistics from the single salinity sample:
hist(salinity$sal)
hist(salinity$sal)
ggplot(data = salinity,
       aes(sample = sal)) +
  geom_qq()

# i believe based on a sinlge sample of n = 28 that a t distrib. describes the sampling distribution!
t.test(salinity$sal) # Get 95% CI for t-distribution


```


Create a function to calculate the mean of different bootstrap samples:

```{r}
mean_fun <- function(x, i) {mean(x[i])}

sal_nc <- salinity$sal

salboot_100 <- boot(data = sal_nc,
                    statistic = mean_fun,
                    R = 100)

salboot_10k <- boot(data = sal_nc,
                    statistic = mean_fun,
                    R = 10000)
salboot_100
salboot_10k

salboot_100_df <- data.frame(bs_mean = salboot_100$t)
salboot_10k_df <- data.frame(bs_mean = salboot_10k$t)

# now lets plot the bootstrapped sampling distribution
p1 <- ggplot(data = salinity, aes(x = sal)) +
  geom_histogram()

p2 <- ggplot(data = salboot_100_df, aes(x = bs_mean)) +
  geom_histogram()

p3 <- ggplot(data = salboot_10k_df, aes(x = bs_mean)) +
  geom_histogram()

# using the patchwork....
p1 + p2 + p3

p1 + p2 / p3

```

```{r}
boot.ci(salboot_10k, conf = 0.95)
```

### Eample of nonlinear least squares

```{r}
df <- read_csv(here("data", "log_growth.csv"))

ggplot(data = df, aes(x = time, y = pop)) +
  geom_point()

ggplot(data = df, aes(x = time, y = log(pop))) +
  geom_point()
```

```{r}
df_exp <- df %>% 
  filter(time < 15) %>% 
  mutate(ln_pop = log(pop))

lm_k <- lm(ln_pop ~ time, data = df_exp)
#lm_k
# Estimate: growth rate = 0.17
# K = 180
# A = 18
```


NOW, NLS:
```{r}
df_nls <- nls(pop ~ K/(1 + A*exp(-r*time)),
              data = df,
              start = list(K = 189, A = 18, r = 0.17),
              trace = TRUE)
summary(df_nls)

model_out <- broom::tidy(df_nls)
model_out
```


```{r}
t_seq <- seq(from = 0, to = 35, length = 200)

# Now make predicitons from our NLS model, using that new sequence of times:
p_predict <- predict(df_nls, newdata = t_seq)

# bind together my time and prediction data:
df_complete <- data.frame(df, p_predict)

ggplot(data = df_complete, aes(x = time, y = pop)) +
  geom_point() +
  geom_line(aes(x = time, y = p_predict)) +
  theme_minimal()
```


```{r}
df_ci <- confint2(df_nls)
df_ci
```


